const BASE_URL = process.env.BASE_URL || 'http://localhost:3000/api'
export const UPLOAD_URL = process.env.UPLOAD_URL || 'https://schance.uploading.asia/api/upload'
export const STORE_IMAGE_URL = process.env.STORE_IMAGE_URL || 'https://schance.uploading.asia'

export const PRODUCT_URL = BASE_URL + '/product'
export const COMPANY_URL = BASE_URL + '/company'
export const LOGIN_URL = BASE_URL + '/auth'
export const REFRESH_TOKEN_URL = BASE_URL + '/auth/refresh-token'
export const ORDER_URL = BASE_URL + '/order'
export const CHANGEPASSWORD_URL = BASE_URL + '/auth/change-password'
export const USER_URL = BASE_URL + '/user?userType=cms'
export const USER_DETAIL_URL = BASE_URL + '/user'
export const CONSUMER_URL = BASE_URL + '/user?userType=fb'
export const USER_CREATE_URL = BASE_URL + '/user/'
